apiVersion: apps/v1
kind: Deployment
metadata:
  name: finc-test
  labels:
    app: finc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finc-test
  template:
    metadata:
      labels:
        app: finc-test
    spec:
      containers:
      - name: finc-test
        image: dhanureddy/finc-test:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: finc-test-service
spec:
  selector:
    app: finc-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
