name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Specify the distribution (e.g., temurin, adopt, zulu)
          java-version: '11'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false

      # Step 3: Set up Maven
      - name: Set up Apache Maven
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: github

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build Docker Image
      - name: Build Docker Image
        run: docker build -t dhanureddy/finc-test:latest .

      # Step 8: Push Docker Image
      - name: Push Docker Image
        run: docker push dhanureddy/finc-test:latest
