name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    env:
      REGISTRY: docker.io
      IMAGE_NAME: finc-test
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          TAG="${{ github.sha }}"
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG} .
      
      - name: Push Docker Image
        run: |
          TAG="${{ github.sha }}"
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}

      - name: Update deployment file
        run: |
          TAG="${{ github.sha }}"
          sed -i "s|image: .*|image: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}|" deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
