name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # # Step 2: Set up JDK 11
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: 11

      # # Step 3: Build the application using Maven
      # - name: Build with Maven
      #   run: mvn clean package

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t dhanureddy/nginx-app:latest .
          docker push dhanureddy/nginx-app:latest

      # Step 7: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.22.0'

      # Step 8: Set up Kubeconfig
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_JSON }}" > kubeconfig.json
          export KUBECONFIG=kubeconfig.json

      # Step 9: Deploy to Kubernetes using the deployment.yaml
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
